name: 'Cypress E2E Testing'

trigger:
- master

stages:
- stage: e2e_testing_stage_chrome
  displayName: 'Chrome E2E Testing'
  jobs:
  - job: e2e_testing_job_chrome
    displayName: 'Run E2E in Chrome'
    pool:
      vmImage: macos-latest
    steps:
      - template: devops/e2e.testing.yml
        parameters:
          browserType: chrome
          
- stage: e2e_testing_stage_edge
  displayName: 'Edge E2E Testing'
  dependsOn: e2e_testing_stage_chrome
  jobs:  
  - job: e2e_testing_job_edge
    displayName: 'Run E2E in Edge'
    pool:
      vmImage: macos-latest
    steps:
      - template: devops/e2e.testing.yml
        parameters:
          browserType: edge

- stage: e2e_testing_stage_electron
  displayName: 'Electron E2E Testing'
  dependsOn: e2e_testing_stage_edge
  jobs:
  - job: e2e_testing_job_electron
    displayName: 'Run E2E in Electron'
    pool:
      vmImage: macos-latest
    steps:
      - template: devops/e2e.testing.yml
        parameters:
          browserType: electron
          
#### Ubuntu OS
- stage: e2e_testing_stage_chrome_ubuntu
  displayName: 'Ubuntu Chrome E2E Testing'
  jobs:
  - job: e2e_testing_job_chrome_ubuntu
    displayName: 'Run E2E in Chrome'
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: devops/e2e.testing.yml
        parameters:
          browserType: chrome
          
- stage: e2e_testing_stage_electron_ubuntu
  displayName: 'Electron E2E Testing Ubuntu'
  dependsOn: e2e_testing_stage_chrome_ubuntu
  jobs:  
  - job: e2e_testing_job_electron_ubuntu
    displayName: 'Run E2E in Electron'
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: devops/e2e.testing.yml
        parameters:
          browserType: electron

- stage: e2e_testing_stage_chromium_ubuntu
  displayName: 'Chromium E2E Testing Ubuntu'
  dependsOn: e2e_testing_stage_chrome_ubuntu
  jobs:
  - job: e2e_testing_job_chromium_ubuntu
    displayName: 'Run E2E in Chromium'
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: devops/e2e.testing.yml
        parameters:
          browserType: edge         